name: farmbeats-sdk-env
channels:
  - conda-forge
  - anaconda
  - defaults
  - defaults
dependencies:
  - python=3.6.9
  - pip=20.1.1=py36_1
  - pip:
    - geopandas==0.7.0
    - pandas==1.0.3
    - numpy==1.18.5
    - rasterio==1.1.5
    - shapely==1.7.0
    - statsmodels==0.12.2
    - h5py==2.10
    - timezonefinder==5.2.0
    - azure_agrifood_farming==1.0.0b1
    - azure-core==1.15.0
    - azureml-core==1.28.0
    - azureml-pipeline==1.28.0
    - azureml-pipeline-core==1.28.0
    - azureml-pipeline-steps==1.28.0
    - azureml-sdk==1.28.0
    - azureml-defaults==1.28.0
    - keras==2.3.1
    - seaborn==0.11.1
    - shapely==1.7.0
    - statsmodels==0.12.2
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - urllib3==1.25.11
    - xarray==0.16.2
    - jupyter
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jupyterlab==2.1.4